- name: Launch Instance(s)
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    key_name: "{{ key_name }}"
    group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: yes
    region: "{{ region }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
    instance_tags: '{"{{ instance_key }}":"{{ instance_value }}"}'
    exact_count: "{{ exact_count }}"
    count_tag: "{{ count_tag }}"
  register: ec2
- name: Add new instance to host group
  add_host: hostname={{ item.public_ip }}
            groupname=launched
  with_items: ec2.instances
- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }}
            port=22
            delay=30
            timeout=320
            state=started
  with_items: ec2.instances
